<?php include 'common/header.php'; ?>

<div class="content">
    <br>
    <!-- Start Content-->
    <div class="container-fluid">

        <!-- Button Datatable -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Invoice

                            <button style="float: right;" type="button" class="btn btn-primary" id="addBtn">
                                Genrate Billing 
                            </button>
                        </h5>
                    </div><!-- end card header -->

                    <div class="card-body">
                        <?php if ($this->session->flashdata('msg')) { ?>
                            <script>alert("<?= $this->session->flashdata('msg'); ?>");</script>
                        <?php } ?>
                        <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th>Generated On</th>
                                    <th>Generated By</th>
                                    <th>Invoice Month</th>
                                    <th>National Users</th>
                                    <th>International Users</th>
                                    <th>National + Int Active</th>
                                    <th>National CDR</th>
                                    <th>Int CDR</th>
                                    <th>Total CDR</th>
                                    <th>Total Calls</th>
                                    <th>Total Minutes</th>
                                    <th>Total Amount</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1; ?>
                            <?php foreach ($data as $row) { ?>
                                <tr>
                                    <td><?php echo $i++; ?></td>
                                    <td><?php echo !empty($row['GenratedOn']) ? date('d M Y H:i', strtotime($row['GenratedOn'])) : '-'; ?></td>
                                    <td><?php echo $row['GenratedBy']; ?></td>
                                    <td>
                                        <?php
                                            $monthNum = (int) $row['InvoiceMonth'];
                                            echo $monthNum > 0 ? date('F', mktime(0, 0, 0, $monthNum, 1)) : $row['InvoiceMonth'];
                                        ?>
                                    </td>
                                    <td><?php echo $row['NationalUserActive']; ?></td>
                                    <td><?php echo $row['IntUser_Active']; ?></td>
                                    <td><?php echo $row['National_Int_Active']; ?></td>
                                    <td><?php echo round($row['National_CDR'], 2); ?></td>
                                    <td><?php echo round($row['IntUer_CDR'], 2); ?></td>
                                    <td><?php echo round($row['National_Int_CDR'], 2); ?></td>
                                    <td><?php echo $row['TotalNumberOfCall']; ?></td>
                                    <td><?php echo $row['TotalMinuteConsumed']; ?></td>
                                    <td><?php echo round($row['TotalAmount'], 2); ?></td>
                                    <td class="text-end">
                                        <?php if (!empty($row['InvoicePdfLink'])) { ?>
                                            <a href="<?php echo $row['InvoicePdfLink']; ?>" target="_blank" class="btn btn-sm bg-primary-subtle" title="View Invoice PDF">
                                                <i class="mdi mdi-file-pdf-box fs-14 text-primary"></i>
                                            </a>
                                        <?php } else { ?>
                                            <span class="text-muted">-</span>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- container-fluid -->
</div> <!-- content -->


<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Add Caller Group</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <!-- Server Side -->
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <form id="callerForm" method="post" action="<?php echo base_url('/') ?>index.php/dashboard/saveinvoice"  class="row g-3">
                            
                            <input type="hidden" name="id" id="callerId" value="0" />

                           <div class="col-md-3">
                                <label for="billing_month" class="form-label">Month</label>
                                <input type="text" class="form-control" id="billing_month" name="billing_month">
                            </div>

                            <div class="col-md-3">
                                <label for="credit_limit" class="form-label">Billing Base On</label>
                                <select class="form-select" name="billing_data" id="billing_data"  required>
                                    <option value="">-- Select --</option>
                                    <option value="student_data">Student Data</option>
                                    <option value="cdr_data">C.D.R Data</option>
                                </select>
                            </div>

                            <div class="col-md-3">
                                <label for="credit_limit" class="form-label">Billing Type</label>
                                <select class="form-select" name="billing_type" id="billing_type"  required>
                                    <option value="">-- Select --</option>
                                    <option value="flat_rate">Student Data</option>
                                    <option value="trai_rate">Trai Rate</option>
                                </select>
                            </div>


                            <div class="col-12">
                                <button style="float: right;" class="btn btn-primary" type="submit">Submit</button>
                            </div>
                        </form>
                    </div> <!-- end card-body -->
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
</div>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js"></script>
<script>
    $('#addBtn').on('click', function() {
        $('#callerForm')[0].reset();
        $('#callerId').val(0);
        $('#staticBackdropLabel').text('Add Caller Group');
        $('button[type="submit"]').text('Submit');
        $('#staticBackdrop').modal('show');
    });

  $('#billing_month').datepicker({
        format: "mm-yyyy",
        startView: "months",
        minViewMode: "months",
        autoclose: true
    });
</script>

<?php include 'common/footer.php'; ?>